#!/bin/bash
set -e
# stop script on frist error

# These commands take this form
# ./ops [script] [option] ...rest

script=${1}
option=${2}
if [ ! -z $script ] ; then shift ; fi
if [ ! -z $option ] ; then shift ; fi
rest="$@"

if [ -z $script ] ; then
  echo "please enter a command after ./ops"

elif [ $script == "setup" ] ; then
  rm -rf node_modules
  yarn install

elif [ $script == "start" ] ; then
  yarn start $rest

elif [ $script == "test" ] ; then
  if [ $option ] && [ $option != "--watch" ] ; then
    yarn test "__tests__/$option.test.js" $rest
  else
    yarn test $option $rest
  fi

elif [ $script == "ship" ] ; then
  yarn build
  surge -d smithandcrown.surge.sh -p ./dist

fi